# application.yml
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: springbank0625@gmail.com
    password: kmifvgcjnwatbfgk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true


jwt:
  signing:
    key: 1920123119201231192012311920123112312321a

logging:
  level:
    root: INFO

management:
  server:
    port: 8030
  endpoints:
    web:
      exposure:
        include: "*"

---

# application-operation.yml
server:
  url: https://beatmate.zapto.org


spring:
  config:
    activate:
      on-profile: operation
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://172.27.0.146:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379
community:
  server: http://community:8081


file:
  dir: /Users/woo/src/app/authentication/upload/image

---

# application-dev.yml
server:
  url: http://localhost
  http: tr
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://mysql:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379

community:
  server: http://community:8081


file:
  dir: /Users/woo/src/app/authentication/upload/image


---

# application-local.dev.yml
server:
  url: http://localhost:8080
spring:
  config:
    activate:
      on-profile: local-dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!
  data:
    redis:
      host: localhost
      port: 6379

community:
  server: http://localhost:8081

file:
  dir: /Users/woo/Desktop/code/appdoc/appdoc-Backend/authentication/upload/image




---

# application-test.yml
server:
  url: http://localhost:8080

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/myapp_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!
  data:
    redis:
      host: localhost
      port: 6379

file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/upload/image

community:
  server: http://localhost:8081

