# application.yml
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: springbank0625@gmail.com
    password: kmifvgcjnwatbfgk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true

jwt:
  signing:
    key: 1920123119201231192012311920123112312321a


---

# application-operation.yml
spring:
  config:
    activate:
      on-profile: operation
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://database-1.codehjwdlrgz.ap-northeast-2.rds.amazonaws.com:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rootroot
server:
  add: http://Docker-spring-env.eba-a3d2ew9y.ap-northeast-2.elasticbeanstalk.com/auth/image
file:
  dir: /usr/src/app/authentication/upload/image

---

# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
server:
  add: http://127.0.0.1/auth/image
file:
  dir: /usr/src/app/authentication/upload/image


---

# application-local.dev.yml
spring:
  config:
    activate:
      on-profile: local-dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!
file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/upload/image

server:
  add: http://127.0.0.1:8080/auth/image

---

# application-test.yml
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/myapp_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!

file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/upload/image

server:
  add: http://127.0.0.1:8080/auth/image

