version: "3"
services:
  mysql: 
    build: ./mysql
    restart: unless-stopped
    container_name: appmysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myapp
  authentication:
    container_name: app_authentication
    build:
      dockerfile: Dockerfile
      context: ./authentication
    volumes:
      - ./authentication/upload/image:/usr/src/app/authentication/upload/image
  community:
    build:
      dockerfile: Dockerfile
      context: ./community
    container_name: app_community
    volumes: 
    - ./community/upload/image:/usr/src/app/community/upload/image
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

