# application.yml
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true

jwt:
  signing:
    key: 1920123119201231192012311920123112312321a


---

# application-operation.yml
spring:
  config:
    activate:
      on-profile: operation
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://database-1.codehjwdlrgz.ap-northeast-2.rds.amazonaws.com:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rootroot
server:
  add: http://Docker-spring-env.eba-a3d2ew9y.ap-northeast-2.elasticbeanstalk.com/community/image

file:
  dir: /usr/src/app/community/upload/image

authentication:
  server: http://Docker-spring-env.eba-a3d2ew9y.ap-northeast-2.elasticbeanstalk.com/auth



---

# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysql:3306/myapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

file:
  dir: /usr/src/app/community/upload/image

server:
  add: http://localhost/community/image

authentication:
  server: http://auth/auth
---

# application-local.dev.yml
spring:
  config:
    activate:
      on-profile: local-dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/myapp1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!
file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/upload/image

server:
  add: http://127.0.0.1:8080/auth/image


authentication:
  server: http://127.0.0.1:8080/auth

---

# application-test.yml
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true



  datasource:
    url: jdbc:mysql://localhost:3306/myapp_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!

file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/community/upload/image

server:
  add: http://127.0.0.1:8081/community/image

authentication:
  server: http://127.0.0.1:8080/auth

