# application.yml
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/webdoc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true

jwt:
  signing:
    key: 1920123119201231192012311920123112312321a

basic:
  image: http://127.0.0.1:8081/static/image/basic.png
---

# application-operation.yml
spring:
  config:
    activate:
      on-profile: operation
  jpa:
    hibernate:
      ddl-auto: update
server:
  add: http://49.50.167.217:8081

file:
  dir: /home/appdoc/media

basic:
  image:

---

# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create

file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/src/main/resources/static/media

server:
  add: http://127.0.0.1:8081

basic:
  image: http://127.0.0.1:8081/static/image/basic.png
---

# application-test.yml
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create



  datasource:
    url: jdbc:mysql://localhost:3306/webdoc_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Opsueaxqx1578!

file:
  dir: /Users/woo/Desktop/code/appdoc-Backend/authentication/src/main/resources/static/media

server:
  add: http://127.0.0.1:8081

