FROM openjdk:17

# 작업 디렉토리 설정
WORKDIR /usr/src/app/community

# 빌드된 JAR 파일 복사
COPY ./build/libs/community-0.0.1-SNAPSHOT.jar ./

# nohup.out 파일 생성
RUN touch nohup.out

# 빌드 후 실행
CMD ["nohup", "java", "-Dspring.profiles.active=dev", "-jar", "./community-0.0.1-SNAPSHOT.jar", ">", "nohup.out", "2>&1"]
