FROM openjdk:17

# 작업 디렉토리 설정
WORKDIR /usr/src/app/community

# 빌드된 JAR 파일 복사
COPY ./build/libs/community-0.0.1-SNAPSHOT.jar ./



# 빌드 후 실행
CMD ["java", "-Dspring.profiles.active=dev", "-jar", "./community-0.0.1-SNAPSHOT.jar"]
